package app.thamani.vetty.core.models

import kotlinx.serialization.Serializable

/**
 * Mirrors the entries in the `vetty_index.json` generated by the KSP plugin.
 * Annotated with `@Serializable` so [SchemaLoader] can parse the index file
 * directly with `kotlinx.serialization`.
 */
@Serializable
data class SchemaIndexEntry(
    val route: String,
    val method: String,
    val schemaFile: String,
    val className: String,
)
