package app.thamani.vetty.core.schema

import app.thamani.vetty.core.models.JsonSchemaNode
import app.thamani.vetty.core.models.LoadedSchema
import app.thamani.vetty.core.models.SchemaIndexEntry
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Loads the JSON Schema files that were generated by the KSP plugin at build time.
 *
 * At runtime, the generated files live in resources under `vetty/`.
 * The index file `vetty/vetty_index.json` maps (route, method) → schemaFile path.
 *
 * SchemaLoader is intentionally lazy: schemas are parsed on first access and
 * then cached in a concurrent map.
 */
object SchemaLoader {
    private val cache = mutableMapOf<String, LoadedSchema>() // "$method:$route" → LoadedSchema
    private val json = Json { ignoreUnknownKeys = true }

    /** Must be called once, e.g. in Application.onCreate() or the Vetty.init() block. */
    fun load(classLoader: ClassLoader = SchemaLoader::class.java.classLoader!!) {
        val indexStream = classLoader.getResourceAsStream("vetty/vetty_index.json") ?: return
        val rawIndex = indexStream.bufferedReader().readText()
        val entries = json.decodeFromString<List<SchemaIndexEntry>>(rawIndex)

        entries.forEach { entry ->
            val stream =
                classLoader.getResourceAsStream(entry.schemaFile) ?: run { return@forEach }
            val rawSchema = stream.bufferedReader().readText()
            val schemaNode = parseSchema(json.parseToJsonElement(rawSchema).jsonObject)
            cache[cacheKey(entry.method, entry.route)] =
                LoadedSchema(
                    route = entry.route,
                    method = entry.method,
                    schema = schemaNode,
                )
        }
    }

    fun findSchema(
        method: String,
        route: String,
    ): LoadedSchema? {
        // Try exact match first, then pattern match (e.g. /users/{id} vs /users/42)
        val exact = cache[cacheKey(method.uppercase(), route)]
        if (exact != null) return exact
        return cache.values.firstOrNull {
            it.method == method.uppercase() &&
                routeMatches(
                    it.route,
                    route,
                )
        }
    }

    fun allSchemas(): List<LoadedSchema> = cache.values.toList()

    // ─── Private ──────────────────────────────────────────────────────────────

    private fun cacheKey(
        method: String,
        route: String,
    ) = "${method.uppercase()}:$route"

    /**
     * Simple path-template matcher.  /users/{id}/posts matches /users/42/posts.
     */
    fun routeMatches(
        template: String,
        actual: String,
    ): Boolean {
        val tParts = template.split("/")
        val aParts = actual.split("?").first().split("/") // strip query string
        if (tParts.size != aParts.size) return false
        return tParts.zip(aParts).all { (t, a) ->
            t == a || (t.startsWith("{") && t.endsWith("}"))
        }
    }

    private fun parseSchema(obj: JsonObject): JsonSchemaNode {
        fun JsonObject.strList(key: String): List<String> =
            this[key]?.let { el ->
                when (el) {
                    is JsonArray -> el.map { it.jsonPrimitive.content }
                    is JsonPrimitive -> listOf(el.content)
                    else -> emptyList()
                }
            } ?: emptyList()

        fun JsonObject.str(key: String): String? = this[key]?.jsonPrimitive?.contentOrNull

        fun JsonObject.int(key: String): Int? = this[key]?.jsonPrimitive?.intOrNull

        fun JsonObject.dbl(key: String): Double? = this[key]?.jsonPrimitive?.doubleOrNull

        fun JsonObject.bool(key: String): Boolean = this[key]?.jsonPrimitive?.booleanOrNull ?: true

        val properties =
            obj["properties"]
                ?.jsonObject
                ?.mapValues { (_, v) -> parseSchema(v.jsonObject) }
                ?: emptyMap()

        val required = obj["required"]?.jsonArray?.map { it.jsonPrimitive.content } ?: emptyList()
        val typeList = obj.strList("type").ifEmpty { listOf("object") }

        return JsonSchemaNode(
            type = typeList,
            properties = properties,
            required = required,
            additionalProperties = obj.bool("additionalProperties"),
            minLength = obj.int("minLength"),
            maxLength = obj.int("maxLength"),
            pattern = obj.str("pattern"),
            enum = obj["enum"]?.jsonArray?.map { it.jsonPrimitive.content },
            minimum = obj.dbl("minimum"),
            maximum = obj.dbl("maximum"),
            minItems = obj.int("minItems"),
            maxItems = obj.int("maxItems"),
            items = obj["items"]?.jsonObject?.let { parseSchema(it) },
            description = obj.str("description"),
        )
    }
}
